export const esportsClubBenefits = [
    "Gain leadership experience as a team captain or club officer",
    "Improve strategic thinking through competitive gameplay",
    "Develop teamwork and communication skills in squad-based games",
    "Learn how to manage a gaming community or Discord server",
    "Get coaching from experienced players to level up your skills",
    "Participate in local and online tournaments for prizes",
    "Build friendships with fellow gamers who share your passion",
    "Enhance problem-solving abilities through fast-paced matches",
    "Gain event management experience by helping organize LAN parties",
    "Improve reaction time and hand-eye coordination",
    "Learn about esports careers (casting, coaching, analytics)",
    "Compete in collegiate leagues for scholarships",
    "Develop confidence by performing under pressure",
    "Get access to high-end gaming setups and equipment",
    "Network with industry professionals and guest speakers",
    "Sharpen decision-making skills in real-time strategy games",
    "Create content (streaming, YouTube) with club support",
    "Learn how to analyze gameplay VODs for self-improvement",
    "Earn recognition through club awards and MVP titles",
    "Experience the thrill of high-stakes competitive play",
    "Discover new games and genres with a supportive group",
    "Improve multitasking abilities in complex games",
    "Gain mentorship from top-ranked players in the club",
    "Build a portfolio for esports or game design careers",
    "Participate in charity gaming marathons (e.g., Extra Life)",
    "Learn about sportsmanship and handling wins/losses gracefully",
    "Develop time management skills balancing gaming & academics",
    "Get feedback on gameplay to identify strengths/weaknesses",
    "Join scrims and practice sessions to refine strategies",
    "Experience team bonding through gaming retreats or meetups",
    "Gain access to exclusive beta tests and game demos",
    "Improve public speaking by casting or hosting events",
    "Learn about game design and balance from a competitive lens",
    "Compete in fantasy esports leagues with club members",
    "Develop resilience by learning from defeats",
    "Get advice on building a gaming PC or optimizing setups",
    "Participate in cosplay or fan art contests for games",
    "Gain volunteer experience helping at gaming conventions",
    "Learn how to negotiate sponsorships for the club",
    "Improve adaptability by mastering meta shifts in games",
    "Build a Twitch/streaming presence with club collaborations",
    "Gain insights into esports psychology and mental training",
    "Compete in club-ranked ladders and earn bragging rights",
    "Learn how to organize and manage a tournament bracket",
    "Develop creativity through game modding or map design",
    "Get tips on maintaining health (posture, eye strain, etc.)",
    "Experience different gaming cultures (KR, EU, NA metas)",
    "Gain credibility by being part of an official CSA club",
    "Improve focus and concentration during long sessions",
    "Learn about esports law and player contracts",
    "Participate in game-specific theorycrafting discussions",
    "Develop a personal brand as a skilled player",
    "Gain experience in shoutcasting and live commentary",
    "Learn how to handle toxicity and maintain positivity",
    "Compete in inter-school rivalries and represent your college",
    "Improve resource management in RTS/MOBA games",
    "Get recommendations for gaming scholarships",
    "Build a network for future esports or tech jobs",
    "Learn how to create highlight reels and gameplay edits",
    "Gain exposure to VR/AR competitive gaming",
    "Develop patience through grinding ranked matches",
    "Get early access to gaming industry trends and news",
    "Participate in speedrunning challenges",
    "Learn about betting analysis and esports statistics",
    "Improve improvisation skills in unpredictable matches",
    "Gain sponsorship opportunities for skilled players",
    "Build a community for niche or retro games",
    "Learn how to balance gaming and real-life responsibilities",
    "Develop quick learning skills for new game releases",
    "Get recognition in school newsletters or esports blogs",
    "Gain experience in graphic design for team logos/jerseys",
    "Learn about the business side of esports (ads, merch)",
    "Improve persuasion skills in team-based decision-making",
    "Compete in meme tournaments or fun custom modes",
    "Develop cultural awareness through global esports",
    "Get advice on avoiding burnout and staying motivated",
    "Learn about hardware specs and performance optimization",
    "Gain opportunities to test unreleased peripherals",
    "Build a reputation as a fair and respected player",
    "Improve adaptability by filling different team roles",
    "Participate in AMAs with semi-pro/pro players",
    "Learn how to set and achieve ranked milestones",
    "Develop a deeper understanding of game lore/storytelling",
    "Get feedback on streaming personality and engagement",
    "Gain insights into patch notes and balance changes",
    "Compete in 1v1 showdowns for club rankings",
    "Learn how to create a gaming resume or portfolio",
    "Improve negotiation skills in team strategy talks",
    "Develop a sense of belonging in a gaming community",
    "Get tips on networking in the esports industry",
    "Learn how to handle stage fright at live events",
    "Gain experience in recruiting and managing teammates",
    "Improve observation skills by studying pro gameplay",
    "Participate in game design feedback sessions with devs",
    "Develop discipline through structured practice routines",
    "Get help balancing academics and esports commitments",
    "Learn about esports history and legendary players",
    "Gain motivation by tracking personal progress over time",
    "Build conflict resolution skills in team disagreements",
    "Improve memory for in-game mechanics and matchups",
    "Experience the joy of teaching new players the ropes"
  ];



export const sportsClubBenefits = [
    "Improve basketball dribbling and shooting skills through structured drills",
    "Develop badminton footwork and racket techniques with expert coaching",
    "Gain leadership experience as a team captain or club vice-president",
    "Compete in inter-school basketball tournaments for trophies and recognition",
    "Participate in friendly badminton matches to build sportsmanship",
    "Learn teamwork through 5v5 basketball scrimmages and strategy sessions",
    "Enhance agility and reflexes with badminton shuttle reaction training",
    "Build endurance with basketball full-court running drills",
    "Make new friends who share a passion for basketball and badminton",
    "Get fit while having fun in weekly club training sessions",
    "Gain confidence by performing in front of crowds during games",
    "Learn how to organize sports events as part of the club committee",
    "Improve hand-eye coordination with badminton net play practice",
    "Develop discipline by committing to regular practice schedules",
    "Receive personalized feedback from experienced players",
    "Join weekend basketball pickup games for casual play",
    "Train in badminton singles and doubles strategies",
    "Earn a varsity letter or club achievement badges",
    "Learn sports first aid and injury prevention techniques",
    "Participate in charity basketball games for good causes",
    "Sharpen decision-making in fast-paced basketball transitions",
    "Master badminton smashes and drop shots through drills",
    "Gain mentorship from senior players in the club",
    "Improve vertical jump with basketball-specific exercises",
    "Compete in ladder tournaments to climb club rankings",
    "Experience the thrill of buzzer-beater basketball games",
    "Learn how to referee or scorekeep for matches",
    "Develop resilience by bouncing back from losses",
    "Access premium basketball courts and badminton facilities",
    "Network with coaches for potential scholarships",
    "Train in zone defense and man-to-man basketball tactics",
    "Perfect badminton serves (short, long, flick) under pressure",
    "Build a sports portfolio for college applications",
    "Enjoy team bonding at post-game pizza nights",
    "Improve spatial awareness in basketball court positioning",
    "Learn how to string a badminton racket properly",
    "Gain volunteer hours by coaching younger students",
    "Stay active and reduce stress through sports",
    "Compete in mixed-gender badminton doubles matches",
    "Develop quick reflexes for basketball steals and blocks",
    "Learn pre-game warmup routines to prevent injuries",
    "Represent the school in regional sports meets",
    "Improve communication skills with on-court callouts",
    "Train in basketball free-throw consistency",
    "Master badminton backhand clears and drives",
    "Gain exposure to sports analytics and stats tracking",
    "Participate in alumni vs. student basketball games",
    "Learn how to create a sports training regimen",
    "Build camaraderie through locker room chats",
    "Improve balance with badminton lunge exercises",
    "Experience the joy of a three-pointer swish",
    "Develop patience while refining techniques",
    "Get featured in school sports highlight reels",
    "Train in basketball pick-and-roll plays",
    "Learn badminton net kill techniques",
    "Gain access to exclusive sports workshops",
    "Compete in 3v3 basketball streetball matches",
    "Improve reaction time with badminton multi-shuttle drills",
    "Celebrate victories with team trophy photos",
    "Learn about sports nutrition and hydration",
    "Develop grit during intense conditioning sessions",
    "Play in themed basketball games (e.g., '80s Night')",
    "Master badminton deception shots (slices, drops)",
    "Gain time-management skills balancing sports and studies",
    "Receive discounts on basketball/badminton gear",
    "Improve lateral movement for basketball defense",
    "Learn how to tape ankles for injury support",
    "Participate in sports science experiments (e.g., jump height tests)",
    "Build a reputation as a clutch player in close games",
    "Train in basketball fast-break strategies",
    "Perfect badminton low serves for tournament play",
    "Gain motivation from coaches’ pep talks",
    "Compete in “King of the Court” badminton challenges",
    "Learn mindfulness techniques for game focus",
    "Develop sportsmanship by shaking hands post-match",
    "Play in outdoor basketball 3-point contests",
    "Improve badminton stamina with endurance rallies",
    "Gain insights from watching game film analysis",
    "Participate in basketball dunk contests (if tall enough!)",
    "Train in badminton doubles rotation strategies",
    "Learn how to scout opponents’ weaknesses",
    "Build lifelong friendships with teammates",
    "Improve basketball passing accuracy (no-look passes!)",
    "Master badminton cross-court smashes",
    "Gain confidence in public speaking as a team rep",
    "Compete in faculty vs. student exhibition matches",
    "Develop a growth mindset through constructive criticism",
    "Play in glow-in-the-dark badminton nights",
    "Learn how to handle pressure during tie-breakers",
    "Improve basketball rebounding positioning",
    "Train in badminton defensive stance drills",
    "Gain leadership skills by mentoring rookies",
    "Participate in basketball-themed trivia nights",
    "Develop quick thinking in fast-break situations",
    "Experience the adrenaline of match point moments",
    "Learn how to maintain sports equipment (e.g., grip tape)",
    "Improve badminton net play reflexes",
    "Gain recognition in school sports award ceremonies",
    "Compete in basketball “Around the World” challenges",
    "Train in badminton jump smashes for offense",
    "Learn conflict resolution through team disagreements",
    "Build endurance with suicide sprint drills",
    "Play in alumni-sponsored badminton leagues",
    "Develop a sense of pride in club achievements"
];